In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv('dataset.csv')

In [3]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [4]:
df.shape

(114000, 21)

In [5]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
text_cols = ['artists', 'album_name', 'track_name', 'track_genre']
df[text_cols] = df[text_cols].fillna('')

In [8]:
df.isnull().sum()

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           114000 non-null  object
 3   album_name        114000 non-null  object
 4   track_name        114000 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [10]:
# Drop these 3 columns
drop_cols = ['Unnamed: 0', 'track_id', 'album_name']
df = df.drop(columns=drop_cols)

In [11]:
df.columns

Index(['artists', 'track_name', 'popularity', 'duration_ms', 'explicit',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'time_signature', 'track_genre'],
      dtype='object')

In [12]:
df['track_name'].duplicated().sum()

np.int64(40391)

In [13]:
df['song_id'] = (
    df['track_name'].astype(str)
    + " - " +
    df['artists'].astype(str)
)

In [14]:
df.head()

,artists,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,song_id
0,Gen Hoshino,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic,Comedy - Gen Hoshino
1,Ben Woodward,Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic,Ghost - Acoustic - Ben Woodward
2,Ingrid Michaelson;ZAYN,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic,To Begin Again - Ingrid Michaelson;ZAYN
3,Kina Grannis,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic,Can't Help Falling In Love - Kina Grannis
4,Chord Overstreet,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic,Hold On - Chord Overstreet

In [15]:
df = df.drop_duplicates(subset='song_id')
df = df.reset_index(drop=True)

In [16]:
features = [
    'danceability',
    'energy',
    'loudness',
    'speechiness',
    'acousticness',
    'instrumentalness',
    'liveness',
    'valence',
    'tempo'
]

In [17]:
X= df[features]

In [18]:
X.head()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,0.676,0.4610,-6.746,0.1430,0.0322,0.000001,0.3580,0.715,87.917
1,0.420,0.1660,-17.235,0.0763,0.9240,0.000006,0.1010,0.267,77.489
2,0.438,0.3590,-9.734,0.0557,0.2100,0.000000,0.1170,0.120,76.332
3,0.266,0.0596,-18.515,0.0363,0.9050,0.000071,0.1320,0.143,181.740
4,0.618,0.4430,-9.681,0.0526,0.4690,0.000000,0.0829,0.167,119.949

In [19]:
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_scaled= sc.fit_transform(X)

In [20]:
song_to_index= pd.Series(df.index, index= df['song_id']).to_dict()

In [21]:
def recommend(song_id, n=10):
    if song_id not in song_to_index:        # check if song exists
        print("Song not found")
        return
        
    song_index = song_to_index[song_id]      # get the selected song
    selected_song = df.loc[song_index]

    print("Selected Song:")
    print(
        selected_song['track_name'],
        "-",
        selected_song['artists'],
        "| Genre:",
        selected_song['track_genre']
    )

    song_genre = selected_song['track_genre']  # Genre filtering

    filtered_df = df[
        df['track_genre'] == song_genre
    ].copy()

    filtered_df = filtered_df.reset_index(drop=True)
    X = filtered_df[features]

    scaler = StandardScaler()              # Scaling
    X_scaled = scaler.fit_transform(X)

    knn = NearestNeighbors(                     # KNN model
        n_neighbors=min(n + 1, len(filtered_df)),
        metric='cosine'
    )

    knn.fit(X_scaled)

    filtered_index = filtered_df[                      # Find selected song in filtered dataset
        filtered_df['song_id'] == song_id
    ].index[0]

    distances, indices = knn.kneighbors(                   # Find nearest neighbors
        X_scaled[filtered_index].reshape(1, -1))
    print(f"\nRecommendations for {song_id}:\n")

    for idx, dist in zip(indices[0][1:], distances[0][1:]):
        row = filtered_df.loc[idx]

        similarity = round((1 - dist) * 100, 2)

        print(
            row['track_name'],
            "-",
            row['artists'],
            "| Similarity:",
            similarity, "%"
        )

In [22]:
recommend("Believer - Imagine Dragons")

Selected Song:
Believer - Imagine Dragons | Genre: rock

Recommendations for Believer - Imagine Dragons:

Thelma + Louise - Bastille | Similarity: 95.09 %
Remind Me - Bastille | Similarity: 90.51 %
Classic - MKTO | Similarity: 90.41 %
Can't Stand Losing You - Remastered 2003 - The Police | Similarity: 82.38 %
Revolution - Bastille | Similarity: 79.66 %
Stressed Out - Twenty One Pilots | Similarity: 79.54 %
Glad You Came - The Wanted | Similarity: 77.97 %
Bones - Imagine Dragons | Similarity: 77.24 %
Remember the Name (feat. Styles of Beyond) - Fort Minor;Styles Of Beyond | Similarity: 76.68 %
On Top Of The World - Imagine Dragons | Similarity: 75.73 %

In [23]:
df[df['track_name'] == 'Believer'][['track_name','artists','track_genre']]

      track_name                 artists    track_genre
23055   Believer                Friction  drum-and-bass
23920   Believer                Fairlane            dub
36549   Believer      Eddie van der Meer         guitar
44156   Believer  Swattrex;The Two Locks         indian
51009   Believer           Mini Pop Kids           kids
65849   Believer         Imagine Dragons           rock
70553   Believer             Lea Michele     show-tunes

In [24]:
def create_tags(row):

    tags = []

    # ---------- Energy ----------
    if row['energy'] >= 0.75:
        tags.append("high_energy")
    elif row['energy'] >= 0.45:
        tags.append("medium_energy")
    else:
        tags.append("low_energy")

    # ---------- Mood (Valence) ----------
    if row['valence'] >= 0.65:
        tags.append("happy")
    elif row['valence'] >= 0.30:
        tags.append("neutral_mood")
    else:
        tags.append("sad")

    # ---------- Danceability ----------
    if row['danceability'] >= 0.75:
        tags.append("danceable")
    elif row['danceability'] >= 0.45:
        tags.append("moderate_dance")
    else:
        tags.append("low_dance")

    # ---------- Acousticness ----------
    if row['acousticness'] >= 0.60:
        tags.append("acoustic")
    else:
        tags.append("non_acoustic")

    # ---------- Speechiness ----------
        # ---------- Speechiness (Updated) ----------
    # Thresholds: >0.66 is likely speech, 0.33-0.66 is mixed, <0.33 is musical
    if row['speechiness'] >= 0.66:
        tags.append("speech_heavy") # Rap, spoken word, podcasts
    elif row['speechiness'] >= 0.33:
        tags.append("mixed_delivery") # Pop with rap verses, rhythmic singing
    else:
        tags.append("melodic") # Pure singing (Crucial for "Infinity")   


    # ------------Tempo--------------
    if row['tempo'] < 80: tags.append("slow_tempo")
    elif row['tempo'] < 120: tags.append("mid_tempo")
    else: tags.append("fast_tempo")
        

    return " ".join(tags)

In [25]:
df['tags'] = df.apply(create_tags, axis=1)

In [26]:
df['text_features'] = (
    df['track_genre'].astype(str) + " " +
    df['tags'].astype(str) + " " +
    df['artists'].astype(str)
)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

text_matrix = tfidf.fit_transform(
    df['text_features']
)

In [28]:
song_id = "Believer - Imagine Dragons"
song_index = song_to_index[song_id]
song_index

65849

In [29]:
from sklearn.metrics.pairwise import cosine_similarity
query_vector= text_matrix[song_index]
text_scores= cosine_similarity(query_vector, text_matrix).flatten()
print(text_scores.shape)

(81344,)

In [30]:
top_indices = text_scores.argsort()[::-1][:10]
print(top_indices)

[65849 65956 65861 65848 65850 65871 65858 65852 65854 65935]

In [31]:
for idx in top_indices:
    row = df.loc[idx]

    print(
        row['track_name'],
        "-",
        row['artists'],
        "| Score:",
        round(text_scores[idx], 4)
    )

Believer - Imagine Dragons | Score: 1.0
It's Time - Imagine Dragons | Score: 0.9588
On Top Of The World - Imagine Dragons | Score: 0.9588
Thunder - Imagine Dragons | Score: 0.951
Bones - Imagine Dragons | Score: 0.9462
Radioactive - Imagine Dragons | Score: 0.9434
Follow You - Imagine Dragons | Score: 0.9344
Whatever It Takes - Imagine Dragons | Score: 0.9344
Bad Liar - Imagine Dragons | Score: 0.9249
Birds - Imagine Dragons | Score: 0.9193

In [32]:
# VERSION1 - AUDIO ENGINE USING MACHINE LEARNING WITH NUMERIC REPRESENTATION
def get_audio_scores(song_id, n=100):

    if song_id not in song_to_index:
        print("Song not found")
        return {}

    song_index = song_to_index[song_id]
    selected_song = df.loc[song_index]
    song_genre = selected_song['track_genre']

    filtered_df = df[
        df['track_genre'] == song_genre
    ].copy()

    filtered_df = filtered_df.reset_index()

    X = filtered_df[features]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    knn = NearestNeighbors(
        n_neighbors=min(n + 1, len(filtered_df)),
        metric='cosine'
    )

    knn.fit(X_scaled)

    filtered_index = filtered_df[
        filtered_df['song_id'] == song_id
    ].index[0]

    distances, indices = knn.kneighbors(
        X_scaled[filtered_index].reshape(1, -1)
    )

    audio_scores = {}

    for idx, dist in zip(indices[0], distances[0]):
        original_index = filtered_df.iloc[idx]['index']
        similarity = 1 - dist
        audio_scores[original_index] = similarity

    return audio_scores

In [33]:
#VERSION2- NLP ENGINE WITH TEXT REPRESENTATION
def get_text_scores(song_id):

    if song_id not in song_to_index:
        print("Song not found")
        return None

    song_index = song_to_index[song_id]

    query_vector = text_matrix[song_index]

    similarities = cosine_similarity(
        query_vector,
        text_matrix
    ).flatten()

    return similarities

In [34]:
# HYBRID VERSION- USE AUDIO AND TEXT VERSION TO PREDICT
def recommend_hybrid(song_id, n=10):

    audio_scores = get_audio_scores(song_id, n=100)
    text_scores = get_text_scores(song_id)

    final_scores = {}

    for idx, audio_score in audio_scores.items():

        text_score = text_scores[idx]

        final_score = (
            0.70 * audio_score +
            0.30 * text_score
        )

        final_scores[idx] = final_score

    sorted_songs = sorted(
        final_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    results = []
    selected_index = song_to_index[song_id]

    for idx, score in sorted_songs:

        if idx == selected_index:
            continue

        row = df.loc[idx]

        results.append({
            "track_name": row['track_name'],
            "artist": row['artists'],
            "genre": row['track_genre'],
            "score": round(score * 100, 2)
        })

        if len(results) == n:
            break

    return results

In [35]:
recommend_hybrid("Believer - Imagine Dragons")

[{'track_name': 'Bones',
  'artist': 'Imagine Dragons',
  'genre': 'rock',
  'score': np.float64(82.45)},
 {'track_name': 'On Top Of The World',
  'artist': 'Imagine Dragons',
  'genre': 'rock',
  'score': np.float64(81.78)},
 {'track_name': 'Thelma + Louise',
  'artist': 'Bastille',
  'genre': 'rock',
  'score': np.float64(73.64)},
 {'track_name': "It's Time",
  'artist': 'Imagine Dragons',
  'genre': 'rock',
  'score': np.float64(69.37)},
 {'track_name': 'Remind Me',
  'artist': 'Bastille',
  'genre': 'rock',
  'score': np.float64(67.79)},
 {'track_name': 'Classic',
  'artist': 'MKTO',
  'genre': 'rock',
  'score': np.float64(67.65)},
 {'track_name': 'Whatever It Takes',
  'artist': 'Imagine Dragons',
  'genre': 'rock',
  'score': np.float64(66.24)},
 {'track_name': "Can't Stand Losing You - Remastered 2003",
  'artist': 'The Police',
  'genre': 'rock',
  'score': np.float64(62.86)},
 {'track_name': 'Revolution',
  'artist': 'Bastille',
  'genre': 'rock',
  'score': np.float64(60.88)},
 {'track_name': 'Stressed Out',
  'artist': 'Twenty One Pilots',
  'genre': 'rock',
  'score': np.float64(59.71)}]

In [36]:
recommend_hybrid("Shape of You - Ed Sheeran")

[{'track_name': 'Shivers',
  'artist': 'Ed Sheeran',
  'genre': 'pop',
  'score': np.float64(82.94)},
 {'track_name': 'Kya Baat Ay',
  'artist': 'Harrdy Sandhu',
  'genre': 'pop',
  'score': np.float64(68.68)},
 {'track_name': 'Naah Goriye (From "Bala")',
  'artist': 'B Praak;Harrdy Sandhu;Swasti Mehul',
  'genre': 'pop',
  'score': np.float64(66.58)},
 {'track_name': 'Naah',
  'artist': 'Harrdy Sandhu',
  'genre': 'pop',
  'score': np.float64(66.2)},
 {'track_name': 'Calm Down (with Selena Gomez)',
  'artist': 'Rema;Selena Gomez',
  'genre': 'pop',
  'score': np.float64(65.84)},
 {'track_name': 'Tauba (feat. Badshah)',
  'artist': 'Payal Dev;Badshah',
  'genre': 'pop',
  'score': np.float64(65.62)},
 {'track_name': 'Coka 2.0 (From "Liger (Telugu)")',
  'artist': 'Jaani;Lijo George-Dj Chetas;Ram Miriyala;Geetha Madhuri;Sukh-E Muzical Doctorz',
  'genre': 'pop',
  'score': np.float64(62.67)},
 {'track_name': 'GODSPEED',
  'artist': 'Tyson Sidhu',
  'genre': 'pop',
  'score': np.float64(62.65)},
 {'track_name': 'Mitti De Tibbe',
  'artist': 'Kaka',
  'genre': 'pop',
  'score': np.float64(61.24)},
 {'track_name': 'Libaas',
  'artist': 'Kaka',
  'genre': 'pop',
  'score': np.float64(61.12)}]

In [37]:
import pickle

artifacts = {
    "df": df,
    "song_to_index": song_to_index,
    "text_matrix": text_matrix,
    "tfidf": tfidf,
    "features": features
}

with open("spotify_model.pkl", "wb") as f:
    pickle.dump(artifacts, f)

In [38]:
with open("spotify_model.pkl", "rb") as f:
    loaded_artifacts = pickle.load(f)

In [39]:
df = loaded_artifacts["df"]
song_to_index = loaded_artifacts["song_to_index"]
text_matrix = loaded_artifacts["text_matrix"]
tfidf = loaded_artifacts["tfidf"]
features = loaded_artifacts["features"]

import os
os.getcwd()

with open(r"C:\Users\karti\app.py", "r") as f:
    print(f.read())